# Generated by Django 4.1.1 on 2022-10-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_product_brand_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
    ]
