# Generated by Django 4.1.1 on 2022-10-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
